### ISSUE TITLE
Prometheus Instrumentation

### ISSUE THREAD

**Issue by hfuss** [hyperledger/firefly-transaction-manager#38]
Similar to https://github.com/hyperledger/firefly/issues/189, it'd be great if FFTM had a Prometheus metrics manager and use https://gitlab.com/hfuss/mux-prometheus in the API server middleware so that all the APIs are automatically instrumented.

Then with a metrics manager, implementations of FFTM like EVMConnect can add their own custom metrics.

**Comment by shorsher** [comment]
See https://github.com/hyperledger/firefly/blob/0b6c289ffee87330f578796d5ece8268216e133f/internal/metrics/prometheus.go for the firefly implementation of http and custom metrics.

**Comment by matthew1001** [comment]
Resolved in https://github.com/hyperledger/firefly-transaction-manager/pull/41
