### ISSUE TITLE
No docker images for v1?

### ISSUE THREAD

**Issue by roderik** [hyperledger/firefly-transaction-manager#48]
Last version in GHCR is ghcr.io/hyperledger/firefly-transaction-manager:v0.9.2 while releases are at 1.1.x

**Comment by nguyer** [comment]
That is correct. In the very early stages of development (pre-1.0) this repo was a standalone executable. At some point during development we decided that it should transition to being a code library that would be included by specific blockchain connector implementations - namely evmconnect at this point. When it made the transition to only being a library, there was no longer an executable binary to publish anymore, so there are no newer docker images. Hope that helps clarify.
