### ISSUE TITLE
Re-architect policy engine as per designs proposed in Miro

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/firefly-transaction-manager#57]
See community call presentation at https://wiki.hyperledger.org/display/FIR/2022-12-14+FireFly+Community+Call for an overview and recording of the presentation

See Miro architecture diagram at https://miro.com/app/board/uXjVOWHk_6s=/?moveToWidget=3458764539804594517&cot=14

**Comment by Chengxuan** [comment]
this work is completed and delivered in the latest release
